---
name: Build docker image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - patches/**
      - scripts/*
  pull_request:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - patches/**
      - scripts/*

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openstack_version:
          - victoria
          - wallaby
          - master
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'
      - run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          OPENSTACK_VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/kolla-ansible
      - run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          OPENSTACK_VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/kolla-ansible
        if: github.ref == 'refs/heads/master'
